{"name": "测试登录功能 - /123456 期望结果: 请输入手机/邮箱/用户名", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "self = <test_login.TestLogin object at 0x0000021DA1A3BCD0>, username = ''\npassword = '123456', expect_result = '请输入手机/邮箱/用户名'\n\n    @allure.story(\"登录功能验证\")\n    @allure.title(\"测试登录功能 - {username}/{password} 期望结果: {expect_result}\")\n    @pytest.mark.parametrize(\"username,password,expect_result\", get_data())\n    def test_login(self, username, password, expect_result):\n        \"\"\"登录测试方法\"\"\"\n        with allure.step(\"执行登录操作\"):\n            self.login_page.page_login(username, password)\n    \n        with allure.step(\"获取错误信息并验证\"):\n            # 获取实际结果\n            actual_result = self.login_page.page_get_error_info()\n    \n            # 添加截图到Allure报告\n            if actual_result != expect_result:\n>               allure.attach(\n                    self.login_page.page_get_img(),\n                    name=f\"login_failure_{username}\",\n                    attachment_type=allure.attachment_type.PNG\n                )\n\ntest_login.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\venv\\lib\\site-packages\\allure_commons\\_allure.py:210: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\pluggy\\_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n..\\venv\\lib\\site-packages\\pluggy\\_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nE:\\Automated_Web_Testing_Demo-main\\Automated_Web_Testing_Demo-main\\venv\\lib\\site-packages\\allure_pytest\\listener.py:252: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\allure_commons\\reporter.py:165: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n..\\venv\\lib\\site-packages\\pluggy\\_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n..\\venv\\lib\\site-packages\\pluggy\\_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x0000021DA158D6D0>\nbody = None, file_name = '382dd520-9cf8-4393-9b7a-64ef27423ee2-attachment.png'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = self._report_dir / file_name\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, str):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\n..\\venv\\lib\\site-packages\\allure_commons\\logger.py:48: TypeError"}, "description": "登录测试方法", "steps": [{"name": "执行登录操作", "status": "passed", "start": 1751014183860, "stop": 1751014184538}, {"name": "获取错误信息并验证", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"C:\\Users\\pc\\Desktop\\webtest\\testcases\\test_login.py\", line 66, in test_login\n    allure.attach(\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Automated_Web_Testing_Demo-main\\Automated_Web_Testing_Demo-main\\venv\\lib\\site-packages\\allure_pytest\\listener.py\", line 252, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\allure_commons\\reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\pc\\Desktop\\webtest\\venv\\lib\\site-packages\\allure_commons\\logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "login_failure_", "source": "382dd520-9cf8-4393-9b7a-64ef27423ee2-attachment.png", "type": "image/png"}], "start": 1751014184538, "stop": 1751014184627}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "'123456'"}, {"name": "expect_result", "value": "'请输入手机/邮箱/用户名'"}], "start": 1751014183860, "stop": 1751014184628, "uuid": "956f64b8-d20d-4223-8ba7-83e328f3d26b", "historyId": "39efe72c910d81f04d6545b37d7e75e3", "testCaseId": "93a39feb8eb701231e6c069b76eeac98", "fullName": "testcases.test_login.TestLogin#test_login", "labels": [{"name": "epic", "value": "登录测试"}, {"name": "feature", "value": "登录功能"}, {"name": "story", "value": "登录功能验证"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-5PHKT4M"}, {"name": "thread", "value": "28896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}